### PR TITLE
ci: refactor action to enable multi-arch builds

### PR DESCRIPTION
**Pull request by MindTooth**
I reworked the action to support multi-arch builds.  Notices that it did not have any and was not able to run it on my Apple Silicon.  Some code is borrowed from the various actions.

Notice `provenance: false` which continue to build the image using older mediatypes.  There is still runtimes used that does not support the new types.

Let me know if you need more from me.  I'm usually next to a computer for an easy fix. 😄 

---

I've published some images [here](https://hub.docker.com/r/mindtooth/reveal-md) to test the changes.

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @MindTooth, sounds like a good idea. Personally I don't know much about this and I don't use it myself either.

Looking at the GitHub Action output it gives an error: "Username and password required"

We're using `repository: webpronl/reveal-md` (note the extra `nl`), might that be related?

**Comment by MindTooth** [comment]
My bad.  Just pushed a fix.

**Comment by MindTooth** [comment]
Hmm. 🤔  Not sure why this does not work.  I’ve been successfully using the action myself.  I did notice that the username needed to be lower case.  Also made sure to use your variable name.  Maybe I’ve typed it wrong.

**Comment by MindTooth** [comment]
Created a test pull request in my own fork, only changed the image name, and was able to login just fine.  https://github.com/MindTooth/reveal-md/pull/1/checks

Care to check if I'm using the correct secret names and if the token is not expired or anything?

**Comment by webpro** [comment]
Yes it that was setup properly I think, but I created a new access token anyway. Trying on master branch now.

**Comment by MindTooth** [comment]
Something else I need to do for moving this forward? 😄

**Comment by webpro** [comment]
Let's see what happens now 🤠

**Comment by MindTooth** [comment]
It works. 🥳  However, it only pushed to `master`.  I don't recall, but that's the correct behavior?  `latest` is last stable release?

**Comment by webpro** [comment]
Yes, the `master` branch is basically the only branch. I just pushed a new release ([v5.5.0](https://github.com/webpro/reveal-md/releases/tag/5.5.0))

**Pull request merged**
