### PR TITLE
add: export pdf with chrome by adding the print-pdf URL query.

### PR DESCRIPTION
**Pull request by jzz4012650**
#122

### CODE REVIEW

**Comment by wwoods** [comment]
Verified, this pull request fixes the issue.

**Comment by webpro** [comment]
Thanks for the PR. Could you please elaborate on how to use this?

**Comment by wwoods** [comment]
See files changed; it works if rather than going to `http://localhost:1948/slides.md` you navigate to `http://localhost:1948/slides.md?print-pdf`.  The browser's native print functionality works with this PR, does not work without it (last worked in reveal-md 0.0.34 from my testing).

Basically, it triggers this functionality in reveal.js: https://github.com/hakimel/reveal.js/#print-stylesheet

**Comment by webpro** [comment]
Thanks. I know about the functionality, it is already there with `--print` (yet buggy).

It doesn't work well for me. I do see the print stylesheet being added, but when viewing/saving as PDF from the print modal in the Chrome browser, I'm getting a white background (i.e. unreadable text).

**Comment by wwoods** [comment]
I had that issue with the latest reveal-md until I merged this pull request.  Then it worked fine.

The Chrome print dialog allows you disable the website background; maybe you have that option unchecked?   Background graphics checkbox in lower-left. 

image

My theme .css also has this, though it would not affect the white background:

```
. reveal .slides section {
    display: flex !important;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
```

**Comment by webpro** [comment]
Ah, now I get it. I'm using the system print dialog by default, instead of Chrome's print dialog. Looks fine to me, thanks.

**Comment by webpro** [comment]
Released in [v0.4.0](https://github.com/webpro/reveal-md/releases/tag/0.4.0)

**Pull request merged**
