### PR TITLE
Move Reveal.initialize after injected scripts

### PR DESCRIPTION
**Pull request by safareli**
This way one can alter 'options'

### CODE REVIEW

**Comment by safareli** [comment]
For example I wanted to have fragments in code blocks which was not possible.

With this change I could just add this script which alters `options`:
```js
options.dependencies.forEach(function(dep) {
  if (dep.src.indexOf("plugin/highlight/highlight.js") == -1) {
    return
  }
  var cb = dep.callback
  dep.callback = function() {
    // more brackets @ https://unicode-table.com/en/search/?q=bracket
    [].forEach.call(document.querySelectorAll('section[data-markdown] pre code'), function(v) {
      var lines = v.innerHTML.split('\n')
      res = ""
      for (var i = 0; i < lines.length; i++) {
        var line = lines[i]
        if (line == '﹇') {
          res += `<span class="fragment">`
        } else if (line == '⎵') {
          res += `</span>`
        } else {
          res += line
            .replace('⁅','<span class="fragment highlight-halffade">')
            .replace('⁆','</span>') + "\n"
        }
      }
      v.innerHTML = res.trim()
    })
    cb();
  }
})
```

and styles
```
.fragment.highlight-halffade {
  opacity: 0.25 !important;
  visibility: visible !important;
}
.fragment.highlight-halffade.visible {
  opacity: 1 !important;
}
```


And this is what my code block looks like:

```haskell
pure ∷ ∀ a . a → Parser a

﹇
> run "Whatever dude" (pure 1)
⁅(Right 1)⁆
⎵

﹇
> run "" (pure 1)
⁅(Right 1)⁆
⎵
```

**Comment by webpro** [comment]
Good idea, thanks @safareli!

**Comment by safareli** [comment]
welcome!

**Comment by safareli** [comment]
@webpro  let me know when you make a new release

**Comment by webpro** [comment]
Done :-)

**Pull request merged**
