### PR TITLE
Single file stand alone rendered presentation + printout

### PR DESCRIPTION
**Pull request by paddelkraft**
I have modified the project so that it can export a rendered presentation as a single standalone html file (fetching all scripts and css from cdnjs) this way you can host a single file on dropbox sharepoint or attach in mails and recipients can view the results without installing anything

`reveal-md presentation.md --standalone` vill create `presentation.reveal.html` in the same folder as presentation.md _(speaker view will not work)_

i have allso created a printout that strips the yaml front matter renders the presentation sa a normal markdown article with styling.

`reveal-md presentation.md --printout` vill create `presentation.printout.html`  in the same folder as presentation.md

### CODE REVIEW

**Comment by webpro** [comment]
I've played with this a bit, and the first thing I noticed was that custom scripts and css are also prefixed with the cdn url (resulting in 404s).

Now I'm thinking, should we really go through this hassle? Users will have two options for this export, and it might not be clear what the difference is between `--static` and `--standalone`.

Earlier on, I've ran the command-line version of inliner on the `--static` output and it worked fine. And to be honest, I don't really mind the file size. If there's no easy way to integrate things with inliner (or something similar), I'd still prefer to document the steps needed to build one standalone file with reveal-md + inliner.

What are your thoughts on this?

**Comment by paddelkraft** [comment]
inliner did not work for me moving the html to a different folder it did not work as the 
deps are not inlined 

but inlining custom scripts and css should not be a big problem

**Comment by webpro** [comment]
I ran `inliner -m index.html > index2.html` and this works pretty well, except that the plugins are still externally fetched. Images are inlined, and speaker view works.

As for the custom scripts and styles, you could just do something like this:
```
echo "console.log(1)" > a.js
echo "console.log(2)" > b.js
echo "body { background-color: green; }" > a.css
reveal-md demo/a.md --static --scripts=a.js,b.js --css=a.css
```
These are also inlined correctly.

**Comment by paddelkraft** [comment]
this worked to inline custom scripts and css on my end.

used an npm package called inline-source that inlines selectively

**Comment by paddelkraft** [comment]
solved conflict with latest pull request on master

**Comment by webpro** [comment]
@paddelkraft I really appreciate your efforts here, but here are my thoughts. Recently, I've made an effort to clean up the code (v0.1.0), and easier maintenance was one of the main reasons. I do see the value of this PR, but in my opinion the cost of more code to maintain, and also more configuration/output options for new users (potentially confusing) are higher. Therefore, I hope you understand I'm closing this PR. Of course you can maintain your own fork and develop it any way you like. Thanks again.

**Comment by paddelkraft** [comment]
@webpro 
I understand.
I really do not want to fork this as it seems like too much hassle to keep up to date. But i would like to extend it. Would you be open to incorporate changes that enables reveal-md to be used as a dependency? exposing functions to parse the standard options options and render the markdown as slides.
this would make it very easy to create a custom extended version of  reveal-md

**Comment by webpro** [comment]
I'm definitely open to such changes, happy to review a PR.

**Pull request closed without merging**
