### PR TITLE
Migrate reveal.js to v4

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Hi 👋! Thank you for this awesome project.

Closes #318 

I wanted to use reveal.js's awesome new [auto-animate feature](https://revealjs.com/auto-animate/) but saw that reveal-md still used version 3.9.2 of reveal.js, so I took a look at upgrading the version.

I mostly followed the [upgrade instructions](https://revealjs.com/upgrading/) from reveal.js, or hammered at stuff until it worked 🔨. 

So please take care while reviewing this PR that I didn't break anything.

It works well for a simple reveal-md project that I tried it on (not many options other than preprocessor)

I haven't updated any code to use the new ES-module system as I am not sure what the goal for browser support is (and it was more work).

Edit: I checked most config options and they all still seem to work.
Edit: Updated some links to the new reveal.js website

### CODE REVIEW

**Comment by davidovich** [comment]
LGTM

I've tried this PR in all of my presentations, and I didn't find any problems.

- fragments
- code highlighting
- fragment code + highlighting
- presentation mode

All work for me.

Nice work @hugo-vrijswijk 

@webpro WDYT ?

**Comment by davidovich** [comment]
Also @hugo-vrijswijk, you might want to add that this closes #315

**Comment by hugo-vrijswijk** [comment]
> Also @hugo-vrijswijk, you might want to add that this closes #315

Done

**Comment by webpro** [comment]
Thanks @hugo-vrijswijk, very much appreciated! I also didn't encounter any issues with various slides, so I've released as [4.0.0-beta.0](https://github.com/webpro/reveal-md/releases/tag/4.0.0-beta.0) and added a section at the top of the readme.

Also thanks to @davidovich for testing!

**Pull request merged**
