### PR TITLE
Added DeckTape Docker printing instructions to README

### PR DESCRIPTION
**Pull request by Ninja73737**
Feel free to make changes if you'd like, I think the instructions are reasonably clear though.

### CODE REVIEW

**Comment by webpro** [comment]
Thanks @Ninja73737!

When I try it, I get this:

```
 ❯ ./bin/reveal-md.js demo/a.md 
Reveal-server started at http://localhost:1948
```

```
❯ docker run --rm -t --net=host -v foo:/slides astefanutti/decktape http://localhost:1948/a.md a.pdf
Loading page http://localhost:1948/a.md ...

Unable to load resource from URL: http://localhost:1948/a.md

Error: net::ERR_CONNECTION_REFUSED at http://localhost:1948/a.md
```

Am I missing something?

**Comment by Ninja73737** [comment]
Hmm that's odd... It appears correct to me, is `http://localhost:1948/a.md` the full url though or is there a `#/` ending when you view it in your browser? That's the only thing I can think of, cause it looks like a networking issue, but you're used `--net=host` so the only thing I can think of is the url...

**Comment by webpro** [comment]
When I add the hash it's stripped off anyway:

```
❯ docker run --rm -t --net=host -v foo:/slides astefanutti/decktape http://localhost:1948/a.md#/ a.pdf
Loading page http://localhost:1948/a.md#/ ...

Unable to load resource from URL: http://localhost:1948/a.md

Error: net::ERR_CONNECTION_REFUSED at http://localhost:1948/a.md#/
```

Sorry, I'm not a Docker expert :)

**Comment by Ninja73737** [comment]
No worries, neither am I. I don't have access to a computer where I can run docker rn, so I can't troubleshoot, on Monday I should be able to though.

If you want to in the meantime though you could see if the issue still happens when you're running reveal-md through Docker too.

**Comment by Ninja73737** [comment]
Figured it out! The issue is that you can't use the `localhost` portion of the URL when you're running DeckTape from Docker and reveal-md locally, not in Docker. There are no issues when reveal-md is also running in Docker. I also checked whether or not the `--host` arg matters for reveal-md, and it doesn't seem to make a difference, so I added an edit to the pull request suggesting that users change the `localhost` portion of the URL to the IP address of their computer when running DeckTape in Docker and reveal-md locally.

Let me know if there's any other issues you run into!

**Comment by webpro** [comment]
Thank you, @Ninja73737! Works like a charm. I'm sure it will help folks out 👍

**Comment by webpro** [comment]
By the way, I did refactor the text a little bit, hope you are OK with it :)

**Comment by Ninja73737** [comment]
Great, glad to help! And definitely no problem with changing the wording!

**Pull request merged**
