### PR TITLE
Fix the inclusion of a custom theme when using `--static`

### PR DESCRIPTION
**Pull request by MartenBE**
This fixes https://github.com/webpro/reveal-md/issues/439 for me.

### CODE REVIEW

**Comment by MartenBE** [comment]
I have tested this in the mean time with both a local css file, and a remote css file using a `https://...` link. Both seem to work fine.

**Comment by NukeManDan** [comment]
@MartenBE  thanks for this! Sadly you branch doesn't work for me in https://github.com/Polkadot-Blockchain-Academy/pba-book - the css is missing from the `bun serve-slides` command, I am sure I have something mangled vs what is "right" for the reveal-md settings and mapping them to files I need in the build and/or serve.

**Comment by MartenBE** [comment]
@NukeManDan I've checked your solution and dived deeper in the code. This solution has been tested with a css file and an css link. It seems to work for both static and watch. Could you recheck if this works?

**Review by NukeManDan — APPROVED** [review]
yup! Now your branch seems to do the trick for me :grin:

**Comment by webpro** [comment]
Thanks, planning to review and go through some issues and pull requests this weekend.

**Comment by MartenBE** [comment]
Is there any update on this? I would like to deploy using github pages to show my colleagues about `reveal-md`, but this prevents me from doing that unfortunately.

**Comment by webpro** [comment]
Thanks @MartenBE and @NukeManDan! This is included in [v5.5.2](https://github.com/webpro/reveal-md/releases/tag/5.5.2)

**Comment by MartenBE** [comment]
@webpro Thank you very much for the update! For my colleagues I created following test case: https://hogenttin.github.io/hogent-revealmd/ . It shows a how to use intro, basic examples and even advanced examples such as iframes, fragments and multicolumn layout. It also demonstrates autodeployment using Github Actions and support for linting and dead link checking.

**Pull request merged**
