### PR TITLE
static html export to stdout

### LINKED ISSUE #47: Feature Request: export to HTML
I love using reveal.md & how it lets me go quickly from outline to a presentation. However, then I find myself wanting to more carefully tweak a presentation & I want access to the full HTML.

I'd love to be able to run `reveal-md slides.md --html` and get a directory called `slides` with an HTML file & required assets.

### PR DESCRIPTION
**Pull request by xy124**
(partly) closes #47 .

Unfortunately printing does not work well with the static exported presentation.

### CODE REVIEW

**Comment by webpro** [comment]
Thanks a lot @xy124, I appreciate the PR. The output HTML is fine, but the assets are missing in the output. I guess most people have reveal-md installed globally. Then after saving the HTML file, it's not clear what to do next. I guess it's best to inline all the assets (even though it would mean a large output file). Maybe it can be done with something like [inliner](https://github.com/remy/inliner)?

**Comment by xy124** [comment]
inliner looks great for compiling everything into one file. At the time I wrote the PR I heavily needed it for a presentation and I had no time to search for something like inliner. I guess after this years examination phase I will take some time to make it export into one file including those assets as well :)

**Comment by webpro** [comment]
OK I'll just leave this PR open until you or someone else can elaborate on it.

**Comment by xy124** [comment]
@webpro: as somebody else already needed this partly feature (see skorokithakis post in #47 ) you maybe want to accept this PR and I will send you another one after implementing the inliner feature? (sorry but atm I'm heavily stuck with the inliner lib of remy, so I think I'll just look for another one the next days, or maybe somebody else already made something to export reveal.js to single html files.)

**Comment by webpro** [comment]
I've merged the changes and released this with [v0.0.26](https://github.com/webpro/reveal-md/releases/tag/0.0.26).

**Pull request merged**
