### PR TITLE
Copy img in html tag

### PR DESCRIPTION
**Pull request by MartenBE**
I use `` tags so I can rescale them using `width`, `height` or `style="width: ...; height: ..."` attributes. Although the live server shows everything fine, the static website missed all the images declared in this way. Upon further inspection, the regex to detect images only detects markdown images and not HTML `` tags. This PR should enable both.

### CODE REVIEW

**Comment by MartenBE** [comment]
Damn, I created the PR first and then saw that a PR for this already exists :p https://github.com/webpro/reveal-md/pull/493

**Comment by webpro** [comment]
Thanks @MartenBE! Except that it also contains the dependency updates. We can just merge that one first once its ready, or fix up this one separately. Up to you, happy to merge either way.

**Comment by MartenBE** [comment]
You can merge the dependancies now, then this PR. I've merged it together.

**Comment by webpro** [comment]
Cherry picked in 358f16281b29e2cb19d46f38c8b86d027ab9bde4

**Comment by webpro** [comment]
Thanks for the fix @MartenBE! Much appreciated.

**Pull request closed without merging**
