### PR TITLE
Add docker packaging

### PR DESCRIPTION
**Pull request by nautikos1235**
Hello all,

I wanted to use your awesome module, but don't want to need node & npm dependencies locally... So I packaged it into docker.

Would you be interested in integrating it?

Thanks for this very easy setup tool :)

### CODE REVIEW

**Comment by nautikos1235** [comment]
Ping @webpro ? :)

**Comment by webpro** [comment]
Thanks @nautikos1235, sorry for my late reply.

That looks useful indeed! But shouldn't reveal-md be published to some public registry? Now, people still need to clone this repo first. How are other similar tools doing this?

Also, I think the `docker build` command should be documented before `docker run`.

**Comment by nautikos1235** [comment]
Hello,

> sorry for my late reply.
No worries, that's kind of you to share & maintain this tool :)

> shouldn't reveal-md be published to some public registry?
Yes it should! I did not want to publish it because I am not the official maintainer of the repository, but usually the maintainer publishes on https://hub.docker.com .
If you agree to integrate this way of packaging & distribution, you can do the following:
- Create (& reserve) the `webpro` account on docker hub
- Merge this pull request
- Create a release with the dockerfile included (3.3.0 for example)
- From your local, run:
```
docker login hub.docker.com
docker build -t webpro/reveal-md:3.3.0 .
docker push webpro/reveal-md:3.3.0
```

Now in my documentation, you'll see I suggest the user to run the image `webpro/reveal-md:latest`.
`latest` is a tag you find on most repository that should mean "the latest stable version of the product". But some people use this tag to publish the "latest commit on their master branch".
You can read about the `docker tag` command to know how to create multiple docker tags from a single built image. You can also have a look at [this article](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375) about the latest tag.

> How are other similar tools doing this?

Either the maintainer manually builds and pushes his docker image to the official repository on each release (or on each push on master), or they configure a CI tool to detect a git tag in the repo & automatically build & push the image to the hub.
If you're interested in going the CI way, maybe I can help setting it up!

> I think the docker build command should be documented before docker run

Well, once the image is published on the hub, you can advertise this command first to allow users to test the image with no further setup. This command will make them pull it from the hub & run a container from this image.
The "build locally" is more for developers or for people who feel more confident building images themselves, seeing the related sources (because you can't really make sure that the docker image you are pulling from the public hub actually contains the code you see in the github repo).

**Comment by nautikos1235** [comment]
Oh I forgot one way to automate, which might actually be the easiest to start =)
You can have a look at docker hub's [automated builds](https://docs.docker.com/docker-hub/builds/), so they watch the github repo directly.

**Comment by nautikos1235** [comment]
I can also create the account and hand it to you after setting up the build automation if you want

**Comment by webpro** [comment]
Thanks a lot for the explanation, @nautikos1235! I'll merge and publish this in a few days when I have time.

**Pull request merged**
