### PR TITLE
WIP fix build vs serve

### LINKED ISSUE #370: serve vs build discrepancy
I have an `assets` folder in my project that contains the `theme` directory and additional assets that are required for my theme (like fonts and images) are stored right next to it. The directory tree looks something like this:

```
assets
├── plugins.js
├── template.html
└── theme
    ├── fonts
    │   ├── ...
    ├── igalia.css
    └── images
        ├── ...
```

since the theme file (`igalia.css`) includes relative paths (`fonts/...`), everything works fine in the default "serve" mode. But when I try to build my slides into static HTML by `--static --static-dirs=assets`, both `igalia.css` and the rest of the folder get copied in different locations. More specifically, here is what the output directory look like:

```
_static
├── _assets
│   ├── assets
│   │   ├── plugins.js
│   │   └── theme
│   │       └── igalia.css
│   └── ...
├── assets
│   ├── plugins.js
│   ├── template.html
│   └── theme
│       ├── fonts
│       │   ├── ...
│       ├── igalia.css
│       └── images
│           ├── ...
...
```

with both `_assets/assets/...` and `assets/...`. The theme stops working as expected in this case, obviously. Any ideas on how this could be fixed?

### PR DESCRIPTION
**Pull request by NukeManDan**
Closes #370

still not quite there, help would be aprreciated!

### CODE REVIEW

**Comment by MartenBE** [comment]
Do you need any help with this?

**Comment by MartenBE** [comment]
I've tried it out and only changing the following fixed my use case (theme is selected for both the listings page as the slides):

```
module.exports.getThemeUrl = (theme, base = '') => {
  const parsedUrl = url.parse(theme);
  if (parsedUrl.host) {
    return theme;
  } else {
    const revealTheme = revealThemes.find(
      themePath => path.basename(themePath).replace(path.extname(themePath), '') === theme
    );
    return base + '/' + (revealTheme ? revealTheme : getAssetPath(theme)); // CHANGED ONLY THIS LINE
  }
};
```

This is the only line I changed from the npm package. @webpro , would this be a valid fix? This is currently the only bug to stop using this at out educational institution.

**Comment by NukeManDan** [comment]
> Do you need any help with this?

Sure - happy to have you replace this PR with another that include a patch and see if that fixes my issues as well :grinning: - we are using this patch at an [educational program in production](https://github.com/polkadot-Blockchain-Academy/pba-book), would be great to see what you are up too as well @MartenBE

**Comment by MartenBE** [comment]
I've submitted https://github.com/webpro/reveal-md/pull/458 , please try it out. It solves my error (but it is a small use case).

**Pull request closed without merging**
